#配置端口号
server:
  port: 8888
#别名定义
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
#配置数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/emp?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
#整合Thymeleaf
  thymeleaf:
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false
    prefix: classpath:/templates
